# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: William J. Brazelton
email: wbrazelton@gmail.com
description: Microbiology, Bioinformatics, Oceanography, Ecology, Astrobiology
url: https://wbrazelton.github.io/
twitter_username: wbrazelton
github_username:  wbrazelton

# Build settings
encoding: utf-8
markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css


exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/nextflu/auspice/index.html"
  - "projects/nextflu/auspice/css/*"
  - "projects/nextflu/auspice/h3n2/*"
  - "projects/nextflu/auspice/h1n1pdm/*"
  - "projects/nextflu/auspice/vic/*"
  - "projects/nextflu/auspice/yam/*"
  - "projects/nextflu/auspice/zika/*"
  - "projects/nextflu/auspice/zibra/*"
  - "projects/nextflu/auspice/muttree/*"
  - "projects/nextflu/auspice/reports/*"
  - "projects/nextflu/auspice/js/*"
  - "projects/nextflu/auspice/cdc/*"
  - "projects/nextflu/auspice/gisaid/*"
  - "projects/auspice/src/*"
  - "projects/siv-cst/beast/main/empiricalTrees/xml/*"
  - "projects/siv-cst/beast/supplement/discreteTraits/xml/*"
  - "projects/siv-cst/beast/supplement/empiricalTrees/xml/*"
  - "projects/h3n2-reassortment/auspice/*"
  - "projects/dengue-antigenic-dynamics/titer_model/seasia_output/*"
  - "projects/h5n1-cambodia/data/tree-jsons/*"
  - "projects/zika-colombia/supplemental-analysis/rarefaction-curves/*"
